using UnifiedAudio.Models;

namespace UnifiedAudio.Helpers;

public static class LiteralCatalog
{
    private static readonly IReadOnlyDictionary<string, (string English, string Chinese)> Values =
        new Dictionary<string, (string, string)>(StringComparer.Ordinal)
        {
            ["Cambiar también la entrada predeterminada de Windows para este perfil"] = ("Also change the Windows default input for this profile", "同时更改此配置的 Windows 默认输入"),
            ["Entrada predeterminada de Windows por perfil"] = ("Per-profile Windows default input", "每个配置的 Windows 默认输入"),
            ["Entrada física global"] = ("Global physical input", "全局物理输入"),
            ["Entrada física global del motor"] = ("Global physical input for the engine", "引擎全局物理输入"),
            ["Salida virtual final"] = ("Final virtual output", "最终虚拟输出"),
            ["Conservar la mezcla de PC al iniciar (elección explícita; se bloquea si Windows Listen crea un loop)"] = ("Keep PC mixing when starting (explicit choice; blocked if Windows Listen creates a loop)", "启动时保留电脑混音（需明确选择；若 Windows Listen 创建回环则阻止）"),
            ["La entrada física global se configura en Entrada y plugins antes de activar el flujo interno."] = ("Configure the global physical input in Input and plug-ins before enabling the internal pipeline.", "启用内部流程前，请在输入和插件中配置全局物理输入。"),
            ["La entrada física global es {0}; los cambios allí afectan a todos los perfiles."] = ("The global physical input is {0}; changes there affect every profile.", "全局物理输入为 {0}；在此处更改会影响所有配置。"),
            ["Override de entrada física por perfil"] = ("Per-profile physical input override", "每个配置的物理输入覆盖"),
            ["Seguir el micrófono físico predeterminado; si Windows apunta a un cable se usa esta entrada como respaldo"] = ("Follow the Windows default physical microphone; use this input as fallback when Windows points to a cable", "跟随 Windows 默认物理麦克风；若 Windows 指向虚拟线缆则使用此输入作为备用"),
            ["Sobrescribir la entrada física global para este perfil"] = ("Override the global physical input for this profile", "覆盖此配置的全局物理输入"),
            ["Abrir carpeta de logs"] = ("Open log folder", "打开日志文件夹"),
            ["Abrir editor"] = ("Open editor", "打开编辑器"),
            ["Acciones de mute"] = ("Mute actions", "静音操作"),
            ["Activar filtrado por aplicación"] = ("Enable per-application filtering", "启用按应用筛选"),
            ["Actualizar aplicaciones"] = ("Refresh applications", "刷新应用"),
            ["Actualizar aplicaciones de audio"] = ("Refresh audio applications", "刷新音频应用"),
            ["Actualizar estado"] = ("Refresh status", "刷新状态"),
            ["Al desbloquear, el overlay muestra borde y barra nativos para moverlo o redimensionarlo. X/Y guardan una posición relativa resistente a cambios de DPI; el color siempre se refuerza con icono y texto."] = ("When unlocked, the circle can be moved or resized. X/Y store a relative position that survives DPI changes; no background is painted outside the circle.", "解锁后可移动或调整圆形悬浮窗。X/Y 保存可适应 DPI 变化的相对位置；圆形之外不会绘制背景。"),
            ["Al desmutear"] = ("When unmuted", "取消静音时"),
            ["Al mutear"] = ("When muted", "静音时"),
            ["Añadir"] = ("Add", "添加"),
            ["Añadir carpeta"] = ("Add folder", "添加文件夹"),
            ["Antes de abrir el motor"] = ("Before opening the engine", "启动引擎前"),
            ["Aplicación vinculada"] = ("Linked application", "关联应用"),
            ["Aplicaciones de audio"] = ("Audio applications", "音频应用"),
            ["Aplicaciones que deben cerrarse al abandonar el perfil"] = ("Applications to close when leaving the profile", "离开配置时要关闭的应用"),
            ["Aplicar a todos los endpoints de grabación activos"] = ("Apply to all active recording endpoints", "应用到所有活动录音端点"),
            ["Aplicar al motor"] = ("Apply to engine", "应用到引擎"),
            ["Aplicar cadena y preset VST3"] = ("Apply VST3 chain and preset", "应用 VST3 链和预设"),
            ["Argumentos"] = ("Arguments", "参数"),
            ["Ataque (ms)"] = ("Attack (ms)", "起音（毫秒）"),
            ["Bajar"] = ("Move down", "下移"),
            ["Bajar audio del PC cuando hablo"] = ("Lower PC audio while I speak", "说话时降低电脑音频"),
            ["Bloquear overlay y hacerlo click-through"] = ("Lock overlay and make it click-through", "锁定悬浮窗并允许点击穿透"),
            ["Bloquear volumen"] = ("Lock volume", "锁定音量"),
            ["Buffer (0 = Auto)"] = ("Buffer (0 = Auto)", "缓冲区（0 = 自动）"),
            ["Buffer solicitado (0 = Auto)"] = ("Requested buffer (0 = Auto)", "请求的缓冲区（0 = 自动）"),
            ["Buscar por plugin o fabricante"] = ("Search by plug-in or manufacturer", "按插件或厂商搜索"),
            ["Bypass / activar"] = ("Bypass / enable", "旁路 / 启用"),
            ["Cadena activa"] = ("Active chain", "活动链"),
            ["Cadena VST3"] = ("VST3 chain", "VST3 链"),
            ["Cantidad (%)"] = ("Amount (%)", "幅度（%）"),
            ["Capturar cadena actual"] = ("Capture current chain", "捕获当前链"),
            ["Carpetas VST3 adicionales"] = ("Additional VST3 folders", "其他 VST3 文件夹"),
            ["Catálogo"] = ("Catalog", "目录"),
            ["Colores de estado"] = ("State colors", "状态颜色"),
            ["Comportamiento"] = ("Behavior", "行为"),
            ["Configura qué llega al endpoint virtual final y cuánto aporta cada fuente."] = ("Configure what reaches the final virtual endpoint and how much each source contributes.", "配置哪些声音进入最终虚拟端点，以及每个来源的音量。"),
            ["Configuración detectada"] = ("Detected configuration", "检测到的配置"),
            ["Configurar mezclador"] = ("Configure mixer", "配置混音器"),
            ["Configurar también el flujo interno"] = ("Also configure the internal flow", "同时配置内部音频流"),
            ["Contrato"] = ("Contract", "协议"),
            ["Controlar endpoints de grabación externos"] = ("Control external recording endpoints", "控制外部录音端点"),
            ["Copiar logs"] = ("Copy logs", "复制日志"),
            ["Copiar selección actual del Mezclador"] = ("Copy current Mixer selection", "复制当前混音器选择"),
            ["Cuándo mostrar el overlay"] = ("When to show the overlay", "何时显示悬浮窗"),
            ["Demora (segundos)"] = ("Delay (seconds)", "延迟（秒）"),
            ["desconectado"] = ("disconnected", "已断开"),
            ["Dispositivo para sonidos de feedback"] = ("Feedback sound output device", "反馈声音输出设备"),
            ["Elegir WAV"] = ("Choose WAV", "选择 WAV"),
            ["Elegir WAV de mute"] = ("Choose mute WAV", "选择静音 WAV"),
            ["Elegir WAV de unmute"] = ("Choose unmute WAV", "选择取消静音 WAV"),
            ["Elegir WAV de PTT activado"] = ("Choose PTT-on WAV", "选择 PTT 开启 WAV"),
            ["Elegir WAV de PTT desactivado"] = ("Choose PTT-off WAV", "选择 PTT 关闭 WAV"),
            ["Ducking"] = ("Ducking", "自动压低"),
            ["Ducking al hablar"] = ("Ducking while speaking", "说话时自动压低"),
            ["Duración del OSD (ms)"] = ("OSD duration (ms)", "OSD 持续时间（毫秒）"),
            ["Ejecutable"] = ("Executable", "可执行文件"),
            ["El color siempre se acompaña de icono y texto accesible."] = ("The visible overlay is only a filled circle; its state is also available to accessibility.", "可见悬浮窗只有一个填充圆形；其状态也提供给无障碍功能。"),
            ["El overlay visible es sólo un círculo relleno; su estado también queda disponible para accesibilidad."] = ("The visible overlay is only a filled circle; its state is also available to accessibility.", "可见悬浮窗只有一个填充圆形；其状态也提供给无障碍功能。"),
            ["El gate interno está después de VST3 y antes de la mezcla. Al asentarse, escribe cero digital exacto aunque un plugin tenga cola."] = ("The internal gate is after VST3 and before mixing. Once settled, it writes exact digital zero even if a plug-in has a tail.", "内部门控位于 VST3 之后、混音之前。稳定后，即使插件仍有尾音，也会输出精确的数字零。"),
            ["El gate interno sigue siendo la autoridad. Este control solo toca endpoints físicos o virtuales que el perfil elija explícitamente; los cambios externos se revisan cada segundo sin bloquear el audio."] = ("The internal gate remains authoritative. This control only touches physical or virtual endpoints explicitly selected by the profile; external changes are checked every second without blocking audio.", "内部门控始终具有最终控制权。此设置只控制配置中明确选择的物理或虚拟端点；每秒检查外部变化，且不阻塞音频。"),
            ["Eliminar"] = ("Delete", "删除"),
            ["Endpoint de audio del sistema"] = ("System audio endpoint", "系统音频端点"),
            ["Seguir la salida predeterminada de Windows; usar el endpoint guardado si el default es un cable"] = ("Follow the Windows default output; use the saved endpoint when the default is a virtual cable", "跟随 Windows 默认输出；若默认设备是虚拟线缆，则使用已保存的端点"),
            ["Endpoints abiertos"] = ("Open endpoints", "已打开端点"),
            ["Endpoints concretos"] = ("Selected endpoints", "指定端点"),
            ["Endpoints externos controlados"] = ("Controlled external endpoints", "受控外部端点"),
            ["Endpoints externos del perfil"] = ("Profile external endpoints", "配置的外部端点"),
            ["Entrada física"] = ("Physical input", "物理输入"),
            ["Entrada que abre el motor"] = ("Input opened by the engine", "引擎打开的输入"),
            ["Seguir el micrófono predeterminado de Windows; usar la entrada guardada si el default es un cable"] = ("Follow the Windows default microphone; use the saved input when the default is a virtual cable", "跟随 Windows 默认麦克风；若默认设备是虚拟线缆，则使用已保存的输入"),
            ["Escala (%)"] = ("Scale (%)", "缩放（%）"),
            ["Espectro de salida · 60 Hz–16 kHz"] = ("Output spectrum · 60 Hz–16 kHz", "输出频谱 · 60 Hz–16 kHz"),
            ["Espectro de salida de 16 bandas"] = ("16-band output spectrum", "16 段输出频谱"),
            ["Estado reproducible del motor, contadores y acceso a logs locales. UnifiedAudio no graba ni sube audio."] = ("Reproducible engine state, counters, and access to local logs. UnifiedAudio does not record or upload audio.", "可复现的引擎状态、计数器和本地日志入口。UnifiedAudio 不录制或上传音频。"),
            ["Excluir"] = ("Exclude", "排除"),
            ["Feedback, OSD y overlay"] = ("Feedback, OSD, and overlay", "反馈、OSD 与悬浮窗"),
            ["Filtrado por aplicación"] = ("Per-application filtering", "按应用筛选"),
            ["Frecuencias"] = ("Frequencies", "频率"),
            ["Guardar acción"] = ("Save action", "保存操作"),
            ["Guardar reglas del perfil"] = ("Save profile rules", "保存配置规则"),
            ["Habilitada"] = ("Enabled", "已启用"),
            ["Hold (ms)"] = ("Hold (ms)", "保持（毫秒）"),
            ["Hook físico: VK_NEXT, scan code 0x51 y tecla no extendida. El evento se pasa también a la aplicación activa."] = ("Physical hook: VK_NEXT, scan code 0x51, non-extended key. The event is also passed to the active application.", "物理钩子：VK_NEXT，扫描码 0x51，非扩展键。事件也会传递给当前应用。"),
            ["Valor inicial físico: NumpadPgDn (VK_NEXT, scan 0x51, no extendida). El campo también acepta botones derecho, central, X1 y X2 del mouse."] = ("Physical default: NumpadPgDn (VK_NEXT, scan 0x51, non-extended). The field also accepts right, middle, X1, and X2 mouse buttons.", "物理默认键：NumpadPgDn（VK_NEXT，扫描码 0x51，非扩展）。该字段也接受鼠标右键、中键、X1 和 X2。"),
            ["Hotkey bloquear/desbloquear overlay"] = ("Overlay lock/unlock hotkey", "悬浮窗锁定/解锁快捷键"),
            ["Hotkey global"] = ("Global hotkey", "全局快捷键"),
            ["Hotkey principal"] = ("Main hotkey", "主快捷键"),
            ["Hotkey mostrar/ocultar overlay"] = ("Overlay show/hide hotkey", "悬浮窗显示/隐藏快捷键"),
            ["Hotkey separada para desmutear"] = ("Separate unmute hotkey", "单独的取消静音快捷键"),
            ["Hotkey separada para mutear"] = ("Separate mute hotkey", "单独的静音快捷键"),
            ["IDs MMDevice"] = ("MMDevice IDs", "MMDevice ID"),
            ["Importar configuraciones anteriores"] = ("Import previous configurations", "导入旧配置"),
            ["Incluir solo las aplicaciones guardadas"] = ("Include only saved applications", "仅包含已保存的应用"),
            ["Las hotkeys separadas usan combinaciones globales de Windows y comprueban conflictos con los perfiles. NumpadPgDn permanece como tecla física para Toggle/PTT/PTM/Híbrido."] = ("Separate hotkeys use global Windows combinations and check for profile conflicts. NumpadPgDn remains the physical key for Toggle/PTT/PTM/Hybrid modes.", "单独快捷键使用 Windows 全局组合键，并检查配置冲突。NumpadPgDn 仍作为切换/PTT/PTM/混合模式的物理按键。"),
            ["Limpiar"] = ("Clear", "清除"),
            ["Limpiar WAV de mute"] = ("Clear mute WAV", "清除静音 WAV"),
            ["Limpiar WAV de unmute"] = ("Clear unmute WAV", "清除取消静音 WAV"),
            ["Limpiar WAV de PTT activado"] = ("Clear PTT-on WAV", "清除 PTT 开启 WAV"),
            ["Limpiar WAV de PTT desactivado"] = ("Clear PTT-off WAV", "清除 PTT 关闭 WAV"),
            ["Localizar y mostrar overlay ahora"] = ("Locate and show overlay now", "立即定位并显示悬浮窗"),
            ["Monitor del OSD"] = ("OSD monitor", "OSD 显示器"),
            ["Automático: monitor de la ventana activa"] = ("Automatic: active window monitor", "自动：活动窗口所在显示器"),
            ["Overlay"] = ("Overlay", "悬浮窗"),
            ["El overlay se mostró en el monitor configurado."] = ("The overlay was shown on the configured monitor.", "悬浮窗已在配置的显示器上显示。"),
            ["Limpiar logs"] = ("Clear logs", "清除日志"),
            ["Logs de aplicación y motor"] = ("Application and engine logs", "应用与引擎日志"),
            ["Logs de UnifiedAudio"] = ("UnifiedAudio logs", "UnifiedAudio 日志"),
            ["Medidores reales"] = ("Live meters", "实时电平表"),
            ["Modo"] = ("Mode", "模式"),
            ["Modo de mezcla"] = ("Mix mode", "混音模式"),
            ["Mostrar OSD temporal sin robar foco"] = ("Show temporary OSD without stealing focus", "显示临时 OSD 且不抢焦点"),
            ["Motor"] = ("Engine", "引擎"),
            ["Mute al activar"] = ("Mute on activation", "启用配置时静音"),
            ["Mute del micrófono"] = ("Microphone mute", "麦克风静音"),
            ["Nivel de sistema"] = ("System level", "系统电平"),
            ["Nivel de voz"] = ("Voice level", "语音电平"),
            ["Nivel final"] = ("Final level", "最终电平"),
            ["No mostrar OSD sobre aplicaciones fullscreen"] = ("Do not show OSD over full-screen applications", "不在全屏应用上显示 OSD"),
            ["Nombre"] = ("Name", "名称"),
            ["Nombre del ejecutable"] = ("Executable name", "可执行文件名"),
            ["Nueva acción"] = ("New action", "新操作"),
            ["Omitir actual"] = ("Skip current", "跳过当前项"),
            ["OSD activo"] = ("Active OSD", "活动 OSD"),
            ["OSD muteado"] = ("Muted OSD", "静音 OSD"),
            ["Overlay always-on-top (bloqueado y click-through)"] = ("Always-on-top overlay (locked and click-through)", "始终置顶悬浮窗（锁定且点击穿透）"),
            ["Overlay hablando"] = ("Speaking overlay", "说话状态悬浮窗"),
            ["Overlay inactivo"] = ("Idle overlay", "空闲状态悬浮窗"),
            ["Overlay muteado"] = ("Muted overlay", "静音状态悬浮窗"),
            ["Opacidad del overlay (%)"] = ("Overlay opacity (%)", "悬浮窗不透明度（%）"),
            ["Panel de grabación de Windows"] = ("Windows recording panel", "Windows 录音面板"),
            ["Parámetro"] = ("Parameter", "参数"),
            ["Passthrough: la aplicación activa también recibe la tecla"] = ("Passthrough: the active application also receives the key", "按键穿透：当前应用也会收到该按键"),
            ["Wildcard: permitir modificadores adicionales"] = ("Wildcard: allow additional modifiers", "通配符：允许附加修饰键"),
            ["Lado de Ctrl"] = ("Ctrl side", "Ctrl 侧") ,
            ["Lado de Alt"] = ("Alt side", "Alt 侧"),
            ["Lado de Shift"] = ("Shift side", "Shift 侧"),
            ["Neutral"] = ("Either side", "任一侧"),
            ["Left"] = ("Left", "左"),
            ["Right"] = ("Right", "右"),
            ["PC (%)"] = ("PC (%)", "电脑音频（%）"),
            ["Perfil"] = ("Profile", "配置"),
            ["Perfiles vinculados a aplicaciones y acciones locales al cambiar mute."] = ("Profiles linked to applications and local actions when mute changes.", "将配置关联到应用，并在静音变化时执行本地操作。"),
            ["Plugin disponible"] = ("Available plug-in", "可用插件"),
            ["Política de arranque del motor"] = ("Engine startup policy", "引擎启动策略"),
            ["Política para aplicaciones nuevas"] = ("Policy for new applications", "新应用策略"),
            ["Posición del OSD"] = ("OSD position", "OSD 位置"),
            ["Posición X relativa (%)"] = ("Relative X position (%)", "相对 X 位置（%）"),
            ["Posición Y relativa (%)"] = ("Relative Y position (%)", "相对 Y 位置（%）"),
            ["Prebuffer"] = ("Prebuffer", "预缓冲"),
            ["Previsualizar e importar"] = ("Preview and import", "预览并导入"),
            ["Proceso"] = ("Process", "进程"),
            ["Quitar"] = ("Remove", "移除"),
            ["Quitar carpeta"] = ("Remove folder", "移除文件夹"),
            ["Reaplicar mute si otra aplicación lo cambia"] = ("Reapply mute if another application changes it", "若其他应用更改静音则重新应用"),
            ["Reglas de aplicaciones del perfil"] = ("Profile application rules", "配置的应用规则"),
            ["Release (ms)"] = ("Release (ms)", "释放（毫秒）"),
            ["Render del endpoint virtual final"] = ("Final virtual endpoint render", "最终虚拟端点输出"),
            ["Retardo de liberación (ms)"] = ("Release delay (ms)", "释放延迟（毫秒）"),
            ["Revisada y de confianza"] = ("Reviewed and trusted", "已审查并信任"),
            ["Salida virtual (render)"] = ("Virtual output (render)", "虚拟输出（渲染）"),
            ["Script PowerShell"] = ("PowerShell script", "PowerShell 脚本"),
            ["Selecciona los endpoints que abre el motor, controla el periodo WASAPI y administra el escaneo VST3 sin bloquear la interfaz."] = ("Select the endpoints opened by the engine, control the WASAPI period, and manage VST3 scanning without blocking the interface.", "选择引擎打开的端点、控制 WASAPI 周期，并在不阻塞界面的情况下管理 VST3 扫描。"),
            ["Solo cuando la aplicación esté en foreground"] = ("Only while the application is in the foreground", "仅当应用位于前台时"),
            ["Solo las marcadas: las no marcadas quedan fuera. Todas salvo las desmarcadas: las aplicaciones nuevas entran automáticamente. Cada regla se conserva aunque la aplicación se cierre."] = ("Only checked apps: unchecked apps stay out. All except unchecked: new apps enter automatically. Every rule is retained after an app closes.", "仅勾选：未勾选的应用不进入。除未勾选外全部：新应用自动进入。应用关闭后仍保留每条规则。"),
            ["Solo se aplica cuando Windows inicia UnifiedAudio. La demora y la espera de proceso son modos mutuamente excluyentes."] = ("Only applies when Windows starts UnifiedAudio. Delay and process-wait modes are mutually exclusive.", "仅在 Windows 启动 UnifiedAudio 时应用。延迟与等待进程模式互斥。"),
            ["Sonidos distintos al mutear y desmutear"] = ("Distinct sounds for mute and unmute", "静音与取消静音使用不同声音"),
            ["Subir"] = ("Move up", "上移"),
            ["Texto desmuteado"] = ("Unmuted text", "取消静音文字"),
            ["Texto muteado"] = ("Muted text", "静音文字"),
            ["Timeout (segundos)"] = ("Timeout (seconds)", "超时（秒）"),
            ["Timeout AFK (ms, 0 = desactivado)"] = ("AFK timeout (ms, 0 = disabled)", "离开超时（毫秒，0 = 禁用）"),
            ["Tipo"] = ("Type", "类型"),
            ["Umbral (dBFS)"] = ("Threshold (dBFS)", "阈值（dBFS）"),
            ["Umbral de actividad (dBFS)"] = ("Activity threshold (dBFS)", "活动阈值（dBFS）"),
            ["Umbral de voz (dBFS)"] = ("Voice threshold (dBFS)", "语音阈值（dBFS）"),
            ["Umbral híbrido (ms)"] = ("Hybrid threshold (ms)", "混合模式阈值（毫秒）"),
            ["Una aplicación por línea. UnifiedAudio solicita un cierre normal de su ventana; nunca fuerza la terminación del proceso."] = ("One application per line. UnifiedAudio requests a normal window close and never force-terminates the process.", "每行一个应用。UnifiedAudio 只请求正常关闭窗口，绝不会强制终止进程。"),
            ["UnifiedAudio detecta archivos de Audio Profiles, Mic Mix, AHK_MicMute y MicVST. Primero muestra un preview; nunca modifica ni elimina el archivo fuente."] = ("UnifiedAudio detects Audio Profiles, Mic Mix, AHK_MicMute, and MicVST files. It shows a preview first and never modifies or deletes the source file.", "UnifiedAudio 可检测 Audio Profiles、Mic Mix、AHK_MicMute 和 MicVST 文件。它会先显示预览，并且绝不修改或删除源文件。"),
            ["Vacío = sonido integrado"] = ("Empty = built-in sound", "留空 = 内置声音"),
            ["Valor desmuteado"] = ("Unmuted value", "取消静音值"),
            ["Valor muteado"] = ("Muted value", "静音值"),
            ["Variables: {profile}, {state}, {isMuted}, {origin}, {inputDevice}, {outputDevice}."] = ("Variables: {profile}, {state}, {isMuted}, {origin}, {inputDevice}, {outputDevice}.", "变量：{profile}、{state}、{isMuted}、{origin}、{inputDevice}、{outputDevice}。"),
            ["VoicemeeterRemote64.dll (opcional; se autodetecta)"] = ("VoicemeeterRemote64.dll (optional; auto-detected)", "VoicemeeterRemote64.dll（可选；自动检测）"),
            ["Volumen (%)"] = ("Volume (%)", "音量（%）"),
            ["Volumen de audio del PC"] = ("PC audio volume", "电脑音频音量"),
            ["Volumen de voz"] = ("Voice volume", "语音音量"),
            ["Volumen en la mezcla"] = ("Volume in mix", "混音音量"),
            ["Volumen objetivo (%)"] = ("Target volume (%)", "目标音量（%）"),
            ["Volumen mute (%)"] = ("Mute volume (%)", "静音音量（%）"),
            ["Volumen unmute (%)"] = ("Unmute volume (%)", "取消静音音量（%）"),
            ["Volumen PTT on (%)"] = ("PTT-on volume (%)", "PTT 开启音量（%）"),
            ["Volumen PTT off (%)"] = ("PTT-off volume (%)", "PTT 关闭音量（%）"),
            ["Volver a detectar"] = ("Detect again", "重新检测"),
            ["Voz (%)"] = ("Voice (%)", "语音（%）"),
            ["WAV personalizado: mute"] = ("Custom WAV: mute", "自定义 WAV：静音"),
            ["WAV personalizado: PTT off"] = ("Custom WAV: PTT off", "自定义 WAV：PTT 关闭"),
            ["WAV personalizado: PTT on"] = ("Custom WAV: PTT on", "自定义 WAV：PTT 开启"),
            ["WAV personalizado: unmute"] = ("Custom WAV: unmute", "自定义 WAV：取消静音"),
            ["Predeterminado de Windows"] = ("Windows default", "Windows 默认设备"),
            ["Entrada → VST3 → Mute → Mezcla → Salida virtual. Cada tarjeta refleja el estado que reporta el motor."] = ("Input → VST3 → Mute → Mix → Virtual output. Each card reflects the state reported by the engine.", "输入 → VST3 → 静音 → 混音 → 虚拟输出。每张卡片都反映引擎报告的真实状态。"),
            ["Solo las marcadas"] = ("Only checked applications", "仅勾选的应用"),
            ["Todas salvo las desmarcadas"] = ("All except unchecked applications", "除未勾选应用外全部"),
            ["Micrófono muteado"] = ("Microphone muted", "麦克风已静音"),
            ["Micrófono activo"] = ("Microphone active", "麦克风活动"),
            ["Micrófono desmuteado"] = ("Microphone unmuted", "麦克风未静音")
            , ["Entrada"] = ("Input", "输入")
            , ["Activa"] = ("Active", "活动")
            , ["Inactiva"] = ("Inactive", "未活动")
            , ["Sin entrada abierta"] = ("No input open", "未打开输入")
            , ["Sin salida abierta"] = ("No output open", "未打开输出")
            , ["{0} plugins"] = ("{0} plug-ins", "{0} 个插件")
            , ["Cadena VST3, {0} plugins"] = ("VST3 chain, {0} plug-ins", "VST3 链，{0} 个插件")
            , ["Escaneo en curso"] = ("Scan in progress", "正在扫描")
            , ["Cadena lista"] = ("Chain ready", "插件链就绪")
            , ["Nivel de entrada"] = ("Input level", "输入电平")
            , ["Nivel tras plugins y gate"] = ("Level after plug-ins and gate", "插件与门控后电平")
            , ["Mute"] = ("Mute", "静音")
            , ["Muteado"] = ("Muted", "已静音")
            , ["Desmuteado"] = ("Unmuted", "未静音")
            , ["Silencio digital establecido"] = ("Digital silence established", "已建立数字静音")
            , ["Gate disponible"] = ("Gate ready", "门控就绪")
            , ["Nivel de voz transmitida"] = ("Transmitted voice level", "传输语音电平")
            , ["Audio del sistema/apps"] = ("System/apps audio", "系统/应用音频")
            , ["Loopback activo"] = ("Loopback active", "回环活动")
            , ["Inactivo"] = ("Inactive", "未活动")
            , ["Sin endpoint"] = ("No endpoint", "无端点")
            , ["{0} · apps {1}/{2}"] = ("{0} · apps {1}/{2}", "{0} · 应用 {1}/{2}")
            , ["Audio del sistema y aplicaciones"] = ("System and application audio", "系统与应用音频")
            , ["Mezcla"] = ("Mix", "混音")
            , ["Procesando"] = ("Processing", "正在处理")
            , ["Detenida"] = ("Stopped", "已停止")
            , ["Voice"] = ("Voice", "语音")
            , ["System"] = ("System", "系统")
            , ["Both"] = ("Both", "两者")
            , ["Mezclador y enrutamiento"] = ("Mixer and routing", "混音与路由")
            , ["Nivel de mezcla"] = ("Mix level", "混音电平")
            , ["Salida virtual"] = ("Virtual output", "虚拟输出")
            , ["Nivel de salida"] = ("Output level", "输出电平")
            , ["Escaneando VST3. Plugins omitidos: {0}."] = ("Scanning VST3. Skipped plug-ins: {0}.", "正在扫描 VST3。已跳过插件：{0}。")
            , ["Plugins: {0}. Omitidos: {1}."] = ("Plug-ins: {0}. Skipped: {1}.", "插件：{0}。已跳过：{1}。")
            , ["Gate asentado: salida de voz en cero digital exacto."] = ("Gate settled: voice output is exact digital zero.", "门控已稳定：语音输出为精确数字零。")
            , ["Aplicando rampa corta antipop."] = ("Applying a short anti-pop ramp.", "正在应用短防爆音渐变。")
            , ["La voz puede pasar al mezclador."] = ("Voice can pass to the mixer.", "语音可以进入混音器。")
            , ["El perfil actual no controla endpoints externos."] = ("The current profile does not control external endpoints.", "当前配置不控制外部端点。")
            , ["{0}: {1}, volumen {2:F0}%"] = ("{0}: {1}, volume {2:F0}%", "{0}：{1}，音量 {2:F0}%")
            , ["{0}: no disponible"] = ("{0}: unavailable", "{0}：不可用")
            , ["muteado"] = ("muted", "已静音")
            , ["activo"] = ("active", "活动")
            , ["Hablando"] = ("Speaking", "正在说话")
            , ["Micrófono: {0}"] = ("Microphone: {0}", "麦克风：{0}")
            , ["Estado del micrófono"] = ("Microphone state", "麦克风状态")
            , ["Activo"] = ("Active", "活动")
            , ["Mutear micrófono"] = ("Mute microphone", "麦克风静音")
            , ["Desmutear micrófono"] = ("Unmute microphone", "取消麦克风静音")
            , ["Muteado, cero digital"] = ("Muted, digital zero", "已静音，数字零")
            , ["Muteando"] = ("Muting", "正在静音")
            , ["{0} en cadena, {1} omitidos, escaneo {2}"] = ("{0} in chain, {1} skipped, scan {2}", "链中 {0} 个，跳过 {1} 个，扫描{2}")
            , ["inactivo"] = ("inactive", "未活动")
            , ["Entrada: {0} · Salida: {1} · Sistema: {2}"] = ("Input: {0} · Output: {1} · System: {2}", "输入：{0} · 输出：{1} · 系统：{2}")
            , ["Entrada: {0} · Salida: {1}"] = ("Input: {0} · Output: {1}", "输入：{0} · 输出：{1}")
            , ["Los logs visibles están en el portapapeles."] = ("The visible logs are on the clipboard.", "可见日志已复制到剪贴板。")
            , ["Se vaciarán los logs locales de UnifiedAudio. Esta acción no cambia perfiles ni audio."] = ("UnifiedAudio local logs will be cleared. This does not change profiles or audio.", "将清除 UnifiedAudio 本地日志。此操作不会更改配置或音频。")
            , ["Confianza explícita"] = ("Explicit trust", "明确授权")
            , ["Ningún programa o script se ejecuta hasta que habilites la acción y marques que revisaste y confías en su contenido."] = ("No program or script runs until you enable the action and confirm that you reviewed and trust its contents.", "在启用操作并确认已审查且信任其内容之前，不会运行任何程序或脚本。")
            , ["Adaptadores opcionales aún no cargados"] = ("Optional adapters not loaded", "可选适配器尚未加载")
            , ["Voicemeeter se habilita como acción opcional mediante su Remote DLL instalada. Aura Sync permanece desactivado sin un SDK/licencia redistribuible verificado."] = ("Voicemeeter is available as an optional action through its installed Remote DLL. Aura Sync remains disabled without a verified redistributable SDK/license.", "Voicemeeter 可通过已安装的 Remote DLL 作为可选操作使用。由于没有已验证的可再分发 SDK/许可证，Aura Sync 保持禁用。")
            , ["Activa · silenciada en Windows"] = ("Active · muted in Windows", "活动 · 已在 Windows 中静音")
            , ["No está emitiendo ahora"] = ("Not producing audio now", "当前未输出音频")
            , ["Regla guardada"] = ("Saved rule", "已保存规则")
            , ["Incluir {0}"] = ("Include {0}", "包含 {0}")
            , ["Nivel de {0}: {1}"] = ("{0} level: {1}", "{0} 电平：{1}")
            , ["Volumen de {0} en la mezcla"] = ("{0} volume in the mix", "{0} 的混音音量")
            , ["Audio del PC"] = ("PC audio", "电脑音频")
            , ["Protección contra loop digital"] = ("Digital loop protection", "数字回环保护")
            , ["Ruta de feedback detectada"] = ("Feedback route detected", "检测到反馈路径")
            , ["La captura de sistema se detuvo y el mezclador volvió a Voz para evitar feedback digital."] = ("System capture was stopped and the mixer returned to Voice to prevent digital feedback.", "系统捕获已停止，混音器已返回语音模式以防止数字反馈。")
            , ["Windows Listen puede devolver la salida final a la captura de sistema. Usa Voz o desactiva Listen antes de mezclar PC."] = ("Windows Listen may return the final output to system capture. Use Voice or disable Listen before mixing PC audio.", "Windows Listen 可能将最终输出返回系统捕获。混合电脑音频前请使用语音模式或禁用 Listen。")
            , ["Windows Listen está activo en la captura de cable, pero no apunta a la fuente de sistema seleccionada."] = ("Windows Listen is active on the cable capture, but it does not target the selected system source.", "Windows Listen 在电缆捕获上处于活动状态，但未指向所选系统源。")
            , ["No detectada"] = ("Not detected", "未检测到")
            , ["Captura de sistema detenida; Voz segura"] = ("System capture stopped; Voice is safe", "系统捕获已停止；语音安全")
            , ["No aplicada"] = ("Not applied", "未应用")
            , ["Inicio seguro en Voz"] = ("Safe Voice start", "安全语音启动")
            , ["La mezcla System/Both anterior no se reactivó al abrir endpoints. Para mezclar audio del PC, selecciónalo explícitamente en Mezclador."] = ("The previous System/Both mix was not reactivated when endpoints opened. To mix PC audio, select it explicitly in Mixer.", "打开端点时未重新启用之前的 System/Both 混音。要混合电脑音频，请在混音器中明确选择。")
            , ["Voz"] = ("Voice", "语音")
            , ["Ambos"] = ("Both", "两者")
            , ["silencio"] = ("silence", "静音")
            , ["Mezclador activo"] = ("Mixer active", "混音器活动")
            , ["Captura de sistema inactiva"] = ("System capture inactive", "系统捕获未活动")
            , ["Solo la voz procesada llega al endpoint final."] = ("Only processed voice reaches the final endpoint.", "只有处理后的语音进入最终端点。")
            , ["Captura por aplicación: {0} activa(s) de {1} configurada(s)."] = ("Per-app capture: {0} active of {1} configured.", "按应用捕获：已配置 {1} 个，活动 {0} 个。")
            , ["Loopback activo en {0}."] = ("Loopback active on {0}.", "{0} 上的回环捕获活动。")
            , ["{0} activa(s) · {1} detectada(s) · máximo 32 capturas activas"] = ("{0} active · {1} detected · up to 32 active captures", "{0} 个活动 · 检测到 {1} 个 · 最多 32 个活动捕获")
            , ["Apps {0}/{1}"] = ("Apps {0}/{1}", "应用 {0}/{1}")
            , ["Endpoint completo"] = ("Full endpoint", "完整端点")
            , ["Voz {0} · PC {1} · Final {2} · {3} · Duck {4:P0} · XRuns {5}/{6}"] = ("Voice {0} · PC {1} · Final {2} · {3} · Duck {4:P0} · XRuns {5}/{6}", "语音 {0} · 电脑 {1} · 最终 {2} · {3} · 压低 {4:P0} · XRuns {5}/{6}")
            , ["Selecciona una entrada y una salida disponibles."] = ("Select an available input and output.", "请选择可用的输入和输出。")
            , ["La operación de escaneo se ejecuta en procesos aislados."] = ("Scanning runs in isolated processes.", "扫描在隔离进程中运行。")
            , ["Escaneando… {0} plugins disponibles; {1} omitidos."] = ("Scanning… {0} plug-ins available; {1} skipped.", "正在扫描… {0} 个插件可用；{1} 个已跳过。")
            , ["{0} plugins en la cadena; {1} disponibles; {2} omitidos."] = ("{0} plug-ins in the chain; {1} available; {2} skipped.", "链中 {0} 个插件；{1} 个可用；{2} 个已跳过。")
            , ["No se detectaron configuraciones compatibles"] = ("No compatible configurations were detected", "未检测到兼容配置")
            , ["Selecciona una configuración"] = ("Select a configuration", "选择配置")
            , ["Importar {0}"] = ("Import {0}", "导入 {0}")
            , ["Importar"] = ("Import", "导入")
            , ["Importación completada"] = ("Import completed", "导入完成")
            , ["No se pudo importar"] = ("Import failed", "无法导入")
            , ["No se pudo elegir el WAV"] = ("Could not choose the WAV", "无法选择 WAV")
            , ["Acción"] = ("Action", "操作")
            , ["Preset vacío: al activar el perfil se quitarán todos los plugins."] = ("Empty preset: activating the profile will remove all plug-ins.", "空预设：启用配置时将移除所有插件。")
            , ["{0} elemento(s), con orden, bypass y estado binario del plugin."] = ("{0} item(s), including order, bypass, and binary plug-in state.", "{0} 个项目，包含顺序、旁路和插件二进制状态。")
            , ["El Mezclador no tiene aplicaciones seleccionadas para copiar."] = ("The Mixer has no selected applications to copy.", "混音器中没有可复制的已选应用。")
            , ["{0} aplicación(es) guardada(s); máximo 12."] = ("{0} saved application(s); maximum 12.", "已保存 {0} 个应用；最多 12 个。")
            , ["Selecciona la entrada interna y el endpoint virtual final."] = ("Select the internal input and final virtual endpoint.", "请选择内部输入和最终虚拟端点。")
            , ["Selecciona al menos un endpoint externo o activa la opción para todos."] = ("Select at least one external endpoint or enable the option for all.", "请选择至少一个外部端点，或启用全部端点选项。")
            , ["Selecciona el endpoint de audio del sistema."] = ("Select the system audio endpoint.", "请选择系统音频端点。")
            , ["Engine v1"] = ("Engine v1", "引擎 v1")
            , ["Input peak"] = ("Input peak", "输入峰值")
            , ["Output peak"] = ("Output peak", "输出峰值")
            , ["System peak"] = ("System peak", "系统峰值")
            , ["Voice peak (post-VST/mute)"] = ("Voice peak (post-VST/mute)", "语音峰值（VST/静音后）")
            , ["Timeout (s)"] = ("Timeout (s)", "超时（秒）")
            , ["C:\\Ruta\\programa.exe"] = ("C:\\Path\\program.exe", "C:\\路径\\程序.exe")
            , ["Mouse izquierdo"] = ("Left mouse button", "鼠标左键")
            , ["Mouse derecho"] = ("Right mouse button", "鼠标右键")
            , ["Mouse central"] = ("Middle mouse button", "鼠标中键")
            , ["Mouse X1"] = ("Mouse X1", "鼠标 X1")
            , ["Mouse X2"] = ("Mouse X2", "鼠标 X2")
            , ["Mouse"] = ("Mouse", "鼠标")
            , ["Capturar siguiente botón del mouse"] = ("Capture next mouse button", "捕获下一个鼠标按钮")
            , ["Pulsa un botón del mouse…"] = ("Press a mouse button…", "按下一个鼠标按钮…")
            , ["Restaurar NumpadPgDn"] = ("Restore NumpadPgDn", "恢复 NumpadPgDn")
            , ["MouseCaptureTimedOut"] = ("Mouse button capture timed out.", "鼠标按钮捕获超时。")
        };

    public static string Get(string? source)
    {
        if (string.IsNullOrWhiteSpace(source) || Loc.Language == AppLanguage.Spanish) return source ?? string.Empty;
        if (!Values.TryGetValue(source, out var value)) return source;
        var language = Loc.Language == AppLanguage.System
            ? System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant()
            : string.Empty;
        var chinese = Loc.Language == AppLanguage.SimplifiedChinese || language == "zh";
        return chinese ? value.Chinese : value.English;
    }
}
